### ISSUE TITLE
Refactor nodes.py

### ISSUE THREAD

**Issue by sdemarch** [NeVerTools/pyNeVer#24]
Restructure the module nodes.py to represent single- and multi-input/output layers

- Delete SingleInputLayerNode and MultiInputLayerNode base classes
- Make LayerNode the base class with a list of inputs and a list of outputs (default 1, enforced in derived layers)

**Comment by darioguidotti** [comment]
We need to keep in mind that if we use the classes of `networks.py` also as containers of nodes defined in `abstraction.py` we need to do one of two things:

1. We need to keep a common ancestor between the concrete and abstract layer nodes (which must have only identifier as attribute).
2. We need to change the current implementation of the abstract layer nodes (#25) so that it make sense to inherit from something defining the attributes `in_dims`, `out_dims`. Maybe by inheriting from the corresponding concrete node instead of keeping  it as an attribute? Keeping it as an attribute is kind of useful because it keep separate the info regarding the original concrete node from the info needed for the abstract transformer forward.

P.s. the overlapping of the nomenclature between abstract interpretation and abstraction in programming is agony.

**Comment by sdemarch** [comment]
I think the best solution is to do the same thing as for the `AbsNeuralNetwork` classes as you say in pt. 2. We have the base class `AbsLayerNode` acting as an interface and then all "concrete abstract" layers inheriting from both the interface and their respective concrete reference node. 

I also think that it can be safe and self-healing to refer to wholly abstract classes as Interfaces

**Comment by sdemarch** [comment]
Cfr. #25 

Also, we implement a getter for `in_dim` in single-input layers and `out_dim` for completeness. It performs nothing, but is the right way to structure the interface of the classes
